# Gradle properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric properties
# check these on https://fabricmc.net/develop if a build fails to resolve dependencies
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9

# Mod properties
mod_version=1.0.0
maven_group=com.shiftedlaw
archives_base_name=rolllaw

# Dependencies
fabric_version=0.107.0+1.21.1
